"""Write the Astro content file for an issue.

Produces `site/src/content/issues/YYYY-WW/index.md`, the structured counterpart
to the flat Substack markdown. The two outputs are independent on purpose: if
the site file is wrong, the newsletter still ships.

Ownership split, because this file gets regenerated when the editor re-runs the
draft on the same week:

* the pipeline owns `year`, `week`, `date`, `articles` and the release tables,
  and refreshes them on every run;
* the editor owns `outro`, `signature`, `ajanlo`, `cover` and each
  article's `imageCredit` — these are read back out of the existing file and
  carried forward untouched;
* `title` and `standfirst` are generated only when the file does not already
  have them, so a headline the editor rewrote by hand is never clobbered.
"""
from __future__ import annotations

import logging
from datetime import date
from pathlib import Path
from typing import Any

import yaml

from src.draft_assembler import CATEGORY_ORDER, DraftEntry
from src.issue_title import IssueTitle
from src.release_picker import ReleaseSnapshot
from src.models import ReleaseEntry
from src.slugify import unique_slugs

logger = logging.getLogger(__name__)

DEFAULT_SITE_ROOT = Path("site")

#: Fields the editor fills in by hand and the pipeline must never overwrite.
#: No `intro`: the site does not render one, so writing it would put a field in
#: the file that silently does nothing.
EDITOR_OWNED = ("outro", "signature", "ajanlo", "cover", "draft")

DEFAULT_SIGNATURE = "— Erik · Pixelposta"

#: The release table columns are narrow at two-up, so platform names are
#: shortened for the web. The Substack markdown keeps the full names.
PLATFORM_SHORT = {
    "PlayStation 5": "PS5",
    "PlayStation 4": "PS4",
    "Xbox Series X": "XSX",
    "Xbox Series X|S": "XSX",
    "Xbox Series X/S": "XSX",
    "Nintendo Switch 2": "Switch 2",
    "Nintendo Switch": "Switch",
}

HEADER_COMMENT = """\
# Generated by the Pixelposta pipeline. Safe to edit by hand.
#
# The pipeline refreshes: year, week, date, articles, releases.
# It preserves anything you write into: title, standfirst,
# outro, signature, ajanlo, cover, and each article's imageCredit.
#
# To add the cover: drop cover.jpg into this folder and uncomment the line
# below. Leaving it pointed at a file that does not exist fails the build.
# cover: ./cover.jpg
#
# To add an article image: drop <slug>.jpg into this folder, using the article's
# own slug as the filename. No frontmatter change needed. Missing file, no image.
"""


class _LiteralStr(str):
    """A string that YAML should emit as a `|` block scalar."""


def _literal_representer(dumper: yaml.Dumper, data: _LiteralStr):
    return dumper.represent_scalar("tag:yaml.org,2002:str", str(data), style="|")


yaml.add_representer(_LiteralStr, _literal_representer)


def saturday_of(year: int, week: int) -> date:
    """The Saturday of an ISO week — the issue's publication date."""
    return date.fromisocalendar(year, week, 6)


def issue_dir(year: int, week: int, site_root: Path = DEFAULT_SITE_ROOT) -> Path:
    return site_root / "src" / "content" / "issues" / f"{year}-{week:02d}"


def _short_platforms(platforms: list[str]) -> str:
    return ", ".join(PLATFORM_SHORT.get(p, p) for p in platforms)


def _release_rows(releases: list[ReleaseEntry]) -> list[dict[str, str]]:
    return [
        {
            "title": r.title,
            "platform": _short_platforms(r.platforms),
            "date": r.release_date.strftime("%m.%d"),
        }
        for r in sorted(releases, key=lambda x: x.release_date)
    ]


def read_existing(path: Path) -> dict[str, Any]:
    """Return the frontmatter of an existing index.md, or {} if there is none.

    A malformed existing file is not worth failing the run over — the whole
    point of this function is to salvage hand-written fields, so if it cannot
    be parsed we log and carry on with a clean generation.
    """
    if not path.exists():
        return {}
    try:
        text = path.read_text(encoding="utf-8")
        if not text.startswith("---"):
            return {}
        _, frontmatter, *_ = text.split("---", 2)
        return yaml.safe_load(frontmatter) or {}
    except Exception as e:
        logger.warning(
            "could not parse existing %s (%s: %s) — regenerating from scratch, "
            "hand-written fields in it will be lost",
            path, type(e).__name__, e,
        )
        return {}


def build_frontmatter(
    entries: list[DraftEntry],
    issue_title: IssueTitle,
    *,
    year: int,
    week: int,
    releases: ReleaseSnapshot | None = None,
    existing: dict[str, Any] | None = None,
) -> dict[str, Any]:
    existing = existing or {}

    ordered = sorted(
        entries,
        key=lambda e: (
            CATEGORY_ORDER.index(e.article.category)
            if e.article.category in CATEGORY_ORDER
            else 99,
            -e.article.relevance_score,
        ),
    )
    slugs = unique_slugs([e.rewrite.hu_title for e in ordered])

    # Image credits are keyed by slug so they survive reordering between runs.
    prior_credits = {
        a.get("slug"): a.get("imageCredit")
        for a in (existing.get("articles") or [])
        if isinstance(a, dict) and a.get("imageCredit")
    }

    articles: list[dict[str, Any]] = []
    for slug, entry in zip(slugs, ordered):
        article: dict[str, Any] = {
            "slug": slug,
            "category": entry.article.category,
            "title": entry.rewrite.hu_title,
            "body": _LiteralStr(entry.rewrite.hu_rewrite.strip() + "\n"),
            "source": entry.article.source,
            "url": entry.article.url,
        }
        if entry.rewrite.hu_kiemelt_info:
            article["kiemelt"] = _LiteralStr(entry.rewrite.hu_kiemelt_info.strip() + "\n")
        if prior_credits.get(slug):
            article["imageCredit"] = prior_credits[slug]
        articles.append(article)

    data: dict[str, Any] = {
        "year": year,
        "week": week,
        "date": saturday_of(year, week).isoformat(),
        "title": existing.get("title") or issue_title.title,
        "standfirst": existing.get("standfirst") or issue_title.standfirst,
        # True on a newly generated issue so it lands in the repo without going
        # live. Whatever is already in the file wins, so re-running the draft on
        # a week that has been published cannot quietly pull it back off the
        # site. `.get("draft", True)` rather than `or True`: a stored False is
        # falsy and would otherwise be overwritten by the default.
        "draft": bool(existing.get("draft", True)),
    }

    # Carry the editor's fields forward verbatim.
    if existing.get("cover"):
        data["cover"] = existing["cover"]
    data["outro"] = _LiteralStr(existing.get("outro") or "")
    data["signature"] = existing.get("signature") or DEFAULT_SIGNATURE

    data["articles"] = articles
    # One flat list. The picker still selects over two separate week windows
    # because that is what stops the model clustering every pick into a single
    # week, but that split is a selection device, not a presentation one.
    data["releases"] = (
        _release_rows([*releases.this_week, *releases.next_week]) if releases else []
    )
    data["ajanlo"] = existing.get("ajanlo") or []

    return data


def write_issue(
    entries: list[DraftEntry],
    issue_title: IssueTitle,
    *,
    year: int,
    week: int,
    releases: ReleaseSnapshot | None = None,
    site_root: Path = DEFAULT_SITE_ROOT,
) -> Path:
    """Write index.md for the issue and return its path."""
    directory = issue_dir(year, week, site_root)
    path = directory / "index.md"

    existing = read_existing(path)
    if existing:
        logger.info("%s already exists — preserving %s", path, ", ".join(EDITOR_OWNED))

    data = build_frontmatter(
        entries, issue_title, year=year, week=week, releases=releases, existing=existing
    )

    body = yaml.dump(
        data,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
        width=88,
    )

    directory.mkdir(parents=True, exist_ok=True)
    path.write_text(f"---\n{HEADER_COMMENT}\n{body}---\n", encoding="utf-8")
    return path
